/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      items: [
        {
          type: 'doc',
          id: 'overview',
          label: 'Intro to GitPOAP',
        },
        {
          type: 'doc',
          id: 'about',
          label: 'About the team',
        },
      ],
    },
    {
      type: 'doc',
      id: 'issuing',
      label: 'Use Cases: Issuing',
    },
    // {
    //   type: 'category',
    //   label: 'Use Cases',
    //   collapsible: true,
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'issuing',
    //       label: 'Issuing',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'after-issuing',
    //       label: 'After Issuing',
    //     },
    //   ],
    // },
    {
      type: 'category',
      label: 'Issuers: Getting Started',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'guide-create',
          label: 'Quickstart guide',
        },
        {
          type: 'doc',
          id: 'types-gp',
          label: 'Types of GitPOAPs',
        },
        {
          type: 'doc',
          id: 'guidelines-issue',
          label: 'Guidelines for issuance',
        },
        {
          type: 'doc',
          id: 'process',
          label: 'Process & timeline',
        },
        {
          type: 'doc',
          id: 'github-bot',
          label: 'GitHub bot',
        },
        {
          type: 'doc',
          id: 'badge',
          label: 'GitHub badge',
        },
        {
          type: 'doc',
          id: 'hackathons',
          label: 'Hackathons',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributors: Getting Started',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'how-to-mint',
          label: 'How to mint',
        },
        {
          type: 'doc',
          id: 'viewing',
          label: 'Viewing my GitPOAPs',
        },
        {
          type: 'doc',
          id: 'how-to-earn',
          label: 'How do I earn a GitPOAP?',
        },
      ],
    },
    {
      type: 'doc',
      id: 'api',
      label: 'Public API',
    },
    {
      type: 'category',
      label: 'Community',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'community-projects',
          label: 'Community-built projects',
        },
        {
          type: 'doc',
          id: 'community-calls',
          label: 'Community calls',
        },
        {
          type: 'link',
          label: 'Discord',
          href: 'https://gitpoap.io/discord',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'guide-create',
          label: 'Creating a GitPOAP',
        },
        {
          type: 'doc',
          id: 'guide-design',
          label: 'Design Guide',
        },
        {
          type: 'doc',
          id: 'guide-mint',
          label: 'Minting a GitPOAP',
        },
        {
          type: 'doc',
          id: 'guide-bot',
          label: 'Installing the GitPOAP GitHub bot',
        },
        {
          type: 'doc',
          id: 'snapshot',
          label: 'Using GitPOAPs: Snapshot',
        },
        {
          type: 'doc',
          id: 'poap-fun',
          label: 'Using GitPOAPs: poap.fun',
        },
      ],
    },
    {
      type: 'doc',
      label: 'FAQ',
      id: 'faq',
    },
    {
      type: 'category',
      label: 'Contact Us',
      collapsible: true,
      items: [
        {
          type: 'link',
          label: 'Discord',
          href: 'https://gitpoap.io/discord',
        },
        {
          type: 'link',
          label: 'Twitter',
          href: 'https://twitter.com/gitpoap',
        },
      ],
    },
    // { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = sidebars;
